name: Test Source Code

on: [push, pull_request]

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Setup for tests
        run: |
          cd tests
          Rscript -e "source('BenefitsCalculator_Unittest.R')"
      - name: Run tests
        run: |
          Rscript -e "source('run_tests.R')"